### ISSUE TITLE
Tensor flow error on deepc05 : AttributeError: type object 'NewBase' has no attribute 'is_abstract'

### ISSUE THREAD

**Issue by sjs7007** [sjs7007/S3Lab#7]
https://github.com/tensorflow/tensorflow/issues/1965

**Comment by sjs7007** [comment]
Fix using : sudo pip install six --upgrade --target="/usr/lib/python2.7/dist-packages"

**Comment by mayank-kgp** [comment]
@sjs7007  Not working

**Comment by mayank-kgp** [comment]
@sjs7007  It worked after sudo pip install six --upgrade --target="/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/"
